---
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    env:
      DISABLE_ERD: "true"

    permissions:
      contents: read

    steps:
      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run local linting (ESLint, Biome, Stylelint)
        run: |
          npm run lint
          npm run stylelint
