---
name: Test

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      DISABLE_ERD: "true"

    permissions:
      contents: read

    steps:
      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: npm run test
